### ISSUE TITLE
Hubitat support?

### ISSUE THREAD

**Issue by jvcaloen** [xtreme22886/SmartThings_UniFi-Presence-Sensor#7]
Hello @xtreme22886 
Thanks a lot for this work, the presence works really well on SmartThings. 
I am migrating to hubitat and was wondering if anyone has been looking into running the smartapp on Hubitat?
If not, I may give it a go myself and share the result.
There are other options, but your solution is more user friendly.
Regards

**Comment by MHedish** [comment]
I'd love to see this forked to Hubitat!  I miss it since moving to HE a year ago.

**Comment by xtreme22886** [comment]
Hello,

Usually when I program something, it's a bit of trial and error with a bunch of research. I don't have a Hubitat so that makes getting this to work on that platform difficult for me. But with that said, you all are in luck! Hubitat is having a spring sale on their hardware ($50 off which ends today) so I just purchased a Hubitat. Once I get it, I'll mess around with it and see if I can port this over.

**Comment by xtreme22886** [comment]
Here you go :). Use the following App code and Driver code for Hubitat support

https://github.com/xtreme22886/Hubitat_UniFi-Presence-Sensor
